import yaml
import os
from flask import Flask, render_template, jsonify, request, redirect, url_for
from scanner.db import get_recent_scans, get_alerts, acknowledge_alert, get_stats, get_alert_scans
from scanner.wifi import scan_wifi

CONFIG_PATHS = [
    "/etc/utr-scanner/config.yaml",
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "config.yaml"),
]


def _get_config_path():
    for path in CONFIG_PATHS:
        if os.path.exists(path):
            return path
    return CONFIG_PATHS[0]


def _save_config(config):
    path = _get_config_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)


def _format_ts(ts):
    """Convert ISO8601 '2026-04-20T14:30:00Z' to '2026-04-20 14:30:00' for readability."""
    if not ts:
        return "(no scans yet)"
    return ts.replace("T", " ").rstrip("Z").split(".")[0]


def _build_ubiquiti_report(config):
    stats = get_stats()
    alert_scans = get_alert_scans()

    target_ssid = config.get("target_ssid") or "(not configured)"
    expected_security = config.get("expected_security", "WPA2")
    scan_interval = config.get("scan_interval", 60)

    first_scan = _format_ts(stats.get("first_scan_time"))
    last_scan_row = stats.get("last_scan") or {}
    last_scan = _format_ts(last_scan_row.get("timestamp"))
    total_scans = stats.get("total_scans", 0)
    total_alerts = stats.get("total_alerts", 0)

    if alert_scans:
        event_lines = [
            "| Timestamp           | Detected | Expected | Signal   |",
            "|---------------------|----------|----------|----------|",
        ]
        for s in alert_scans:
            ts = _format_ts(s.get("timestamp"))
            detected = (s.get("security") or "Unknown")[:8]
            signal = s.get("signal_dbm")
            signal_str = f"{signal} dBm" if signal is not None else "--"
            event_lines.append(
                f"| {ts:<19} | {detected:<8} | {expected_security:<8} | {signal_str:<8} |"
            )
        events_block = "\n".join(event_lines)
    else:
        events_block = "_No downgrade events recorded during the monitoring window._"

    return (
        "## UniFi Travel Router — Unsecure WiFi Bug Report\n\n"
        "### My Setup (please fill in)\n"
        "- UTR firmware version: [FILL IN]\n"
        "- Gateway model + firmware: [FILL IN]\n"
        "- Network controller version: [FILL IN]\n"
        "- UTR configuration: [adopted to home site / standalone SSID]\n"
        "- Uplink type during bug: [hotel / airplane / home / other]\n\n"
        "### Scanner Setup\n"
        f"- Target SSID: {target_ssid}\n"
        f"- Expected security: {expected_security}\n"
        f"- Scan interval: {scan_interval}s\n"
        f"- Monitoring window: {first_scan} → {last_scan} (UTC)\n"
        f"- Total scans: {total_scans}\n"
        f"- Downgrade events detected: {total_alerts}\n\n"
        "### Downgrade Events (UTC)\n"
        f"{events_block}\n\n"
        "### Notes (please fill in)\n"
        "What were you doing when the bug appeared? Uplink change, reboot, new location, etc.?\n"
        "[FILL IN]\n\n"
        "---\n"
        "Generated by UTR Scanner — https://github.com/Crosstalk-Solutions/utr-scanner\n"
    )


def create_app(config, scanner_state):
    app = Flask(
        __name__,
        template_folder="../templates",
        static_folder="../static",
    )

    @app.route("/")
    def index():
        stats = get_stats()
        needs_setup = config.get("target_ssid") in (None, "", "MyNetwork")
        return render_template(
            "index.html",
            config=config,
            state=scanner_state,
            stats=stats,
            needs_setup=needs_setup,
        )

    @app.route("/setup")
    def setup():
        return render_template(
            "setup.html",
            config=config,
        )

    @app.route("/api/scans")
    def api_scans():
        limit = request.args.get("limit", 500, type=int)
        return jsonify(get_recent_scans(limit))

    @app.route("/api/alerts")
    def api_alerts():
        return jsonify(get_alerts(acknowledged=False))

    @app.route("/api/stats")
    def api_stats():
        stats = get_stats()
        stats["scanner_state"] = scanner_state
        return jsonify(stats)

    @app.route("/api/alerts/<int:alert_id>/acknowledge", methods=["POST"])
    def api_acknowledge(alert_id):
        acknowledge_alert(alert_id)
        return jsonify({"ok": True})

    @app.route("/api/export-report")
    def api_export_report():
        return jsonify({"report": _build_ubiquiti_report(config)})

    @app.route("/api/scan-networks")
    def api_scan_networks():
        interface = config.get("wifi_interface", "wlan0")
        networks = scan_wifi(interface)
        # Deduplicate by SSID, keeping strongest signal
        seen = {}
        for net in networks:
            ssid = net["ssid"]
            if not ssid or "\\x00" in ssid:
                continue
            if ssid not in seen or (net.get("signal_dbm") or -100) > (seen[ssid].get("signal_dbm") or -100):
                seen[ssid] = net
        unique = sorted(seen.values(), key=lambda n: n.get("signal_dbm") or -100, reverse=True)
        return jsonify(unique)

    @app.route("/api/config", methods=["GET"])
    def api_get_config():
        return jsonify({
            "target_ssid": config.get("target_ssid", ""),
            "expected_security": config.get("expected_security", "WPA2"),
            "scan_interval": config.get("scan_interval", 60),
            "wifi_interface": config.get("wifi_interface", "wlan0"),
        })

    @app.route("/api/config", methods=["POST"])
    def api_save_config():
        data = request.get_json()
        if not data or not data.get("target_ssid"):
            return jsonify({"error": "target_ssid is required"}), 400

        config["target_ssid"] = data["target_ssid"]
        config["expected_security"] = data.get("expected_security", "WPA2")
        if data.get("scan_interval"):
            config["scan_interval"] = int(data["scan_interval"])

        _save_config(config)

        # Reset scanner state so it picks up the new SSID immediately
        scanner_state["status"] = "running"
        scanner_state["last_security"] = None
        scanner_state["consecutive_alerts"] = 0

        return jsonify({"ok": True, "message": "Config saved. Scanner will use new settings on next scan cycle."})

    return app
